services:
  comfyui:
    image: comfyui-rocm
    container_name: comfyui-rocm
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - HIP_VISIBLE_DEVICES=0
      - PYTORCH_HIP_ALLOC_CONF=expandable_segments:True
    network_mode: host
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - comfyui-data:/comfyui
    stdin_open: true
    tty: true
    restart: "always"

volumes:
  comfyui-data: